development:
  adapter: postgresql
  database: phonebook_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: phonebook_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: phonebook_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
